### ISSUE TITLE
getting error while trying to run "FlappyBird.jar" file.

### ISSUE THREAD

**Issue by prateekgoelmzn** [kingyuluk/FlappyBird#13]
Getting below error:
`
java.io.FileNotFoundException: resources/img/background.png (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:212)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:154)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:109)
	at com.kingyu.flappybird.util.GameUtil.loadBufferedImage(GameUtil.java:30)
	at com.kingyu.flappybird.component.GameBackground.<clinit>(GameBackground.java:25)
	at com.kingyu.flappybird.app.Game.initGame(Game.java:116)
	at com.kingyu.flappybird.app.Game.<init>(Game.java:46)
	at com.kingyu.flappybird.app.App.main(App.java:12)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.kingyu.flappybird.app.Game.initGame(Game.java:116)
	at com.kingyu.flappybird.app.Game.<init>(Game.java:46)
	at com.kingyu.flappybird.app.App.main(App.java:12)
Caused by: java.lang.NullPointerException
	at com.kingyu.flappybird.component.GameBackground.<clinit>(GameBackground.java:27)
	... 3 more

`

**Comment by PDPENG** [comment]
Try switching to or installing JDK1.8 to troubleshoot environment issues

**Comment by heiyt** [comment]
Does this call Swing bag?

**Comment by PDPENG** [comment]
> Does this call Swing bag?

What does you mean?

**Comment by heiyt** [comment]
这个是用swing做的吗
